// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhwZNdrCMS0WS6NRPk33rdMJ77bGGV-4',
    appId: '1:792152744175:web:b776e5ece48cb7508d3b1a',
    messagingSenderId: '792152744175',
    projectId: 'auth-ed573',
    authDomain: 'auth-ed573.firebaseapp.com',
    storageBucket: 'auth-ed573.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAldKWqpZoKBQxHY8OsWNkOcnrzoTHh20o',
    appId: '1:792152744175:android:5a38398c415469c28d3b1a',
    messagingSenderId: '792152744175',
    projectId: 'auth-ed573',
    storageBucket: 'auth-ed573.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9JYCH1N6uh7g2zd8xOSgOUMN2GWcIGXA',
    appId: '1:792152744175:ios:ffba26ab0d65dda68d3b1a',
    messagingSenderId: '792152744175',
    projectId: 'auth-ed573',
    storageBucket: 'auth-ed573.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9JYCH1N6uh7g2zd8xOSgOUMN2GWcIGXA',
    appId: '1:792152744175:ios:72d1656e11addfef8d3b1a',
    messagingSenderId: '792152744175',
    projectId: 'auth-ed573',
    storageBucket: 'auth-ed573.appspot.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
